---
- name: Simple OpenStack Deployment Example - RHEL
  hosts: localhost
  gather_facts: False
  vars:
    instance_name: rhel
    os_keystone_url: http://127.0.0.1:5000/v2.0/
    os_username: demo
    os_password: secret
    os_tenant: demo
    os_network_id: 515c7188-1091-4d9e-a43b-ab2c6a4401a6
    os_flavor_id: 2
    os_key_name: demo
  
  tasks:
  - name: Launch RHEL Instance
    os_server:
      state: present
      auth:
        auth_url: "{{ os_keystone_url }}"
        username: "{{ os_username }}"
        password: "{{ os_password }}"
        project_name: "{{ os_tenant }}"
      name: "{{ instance_name }}"
      image: rhel-guest-image-7.2-20151102.0
      key_name: "{{ os_key_name }}"
      timeout: 200
      flavor: "{{ os_flavor_id }}"
      floating_ip_pools: "vlan177"
      nics:
        - net-id: "{{ os_network_id }}"
      meta:
        hostname: "{{ instance_name }}.openstacklocal"
    register: nova
