---
- name: Simple OpenStack Deployment Example - RHEL
  hosts: localhost
  gather_facts: False
  vars:
    instance_name: rhel
    os_keystone_url: http://127.0.0.1:5000/v2.0/
    os_username: demo
    os_password: secret
    os_tenant: demo
    os_network_id: 515c7188-1091-4d9e-a43b-ab2c6a4401a6
    os_flavor_id: 2
    os_key_name: demo
  
  tasks:
  - name: Launch RHEL Instance
    nova_compute:
      state: present
      auth_url: "{{ os_keystone_url }}"
      login_username: "{{ os_username }}"
      login_password: "{{ os_password }}"
      login_tenant_name: "{{ os_tenant }}"
      name: "{{ instance_name }}"
      image_name: rhel-guest-image-7.2-20151102.0
      key_name: "{{ os_key_name }}"
      wait_for: 200
      flavor_id: "{{ os_flavor_id }}"
      nics:
        - net-id: "{{ os_network_id }}"
      meta:
        hostname: "{{ instance_name }}.openstacklocal"
    register: nova
  
  - name: Wait for Host to be Available
    wait_for: host={{ nova.private_ip }} port=22 delay=10
  
  - name: Add CentOS Instance to Inventory
    add_host: name="{{ instance_name }}" ansible_ssh_user=cloud-user
              ansible_ssh_host={{ nova.private_ip }} 
              ansible_sudo

- name: Ping new host
  hosts: "{{ instance_name }}"
  
  tasks:
  - ping:
